### ISSUE TITLE
ReadMe.md

### ISSUE THREAD

**Issue by Estebene** [NfagieYansaneh/Possession#1]
In order to let the people testing your code understand the program and thus be able to fully test it, could you add a bare bones read me that just tells the users what the keys do (movement, actions etc).

**Comment by NfagieYansaneh** [comment]
Oh yeah, I will add controls in the readme for v0.2.0-alpha.1 which will be coming out today or tomorrow. This update will now let the possession orb gravitate towards players. Just sorta busy a little bit right now because I got to write up a physics report for school.

Would you also like me to upload my game design document to the github so you can understand the idea of the game and its purpose?

**Comment by Estebene** [comment]
That would be great

**Comment by NfagieYansaneh** [comment]
Hey, soz but I cant upload v0.2.0-alpha.1 right now because I am just caught up with an upcoming chemistry test. However, I did implement the ability for the crown to gravitate towards characters. Although, this actually caused the crown to slingshot around people more often then I liked. 

![9BKXBY9yfY](https://user-images.githubusercontent.com/60585677/120074111-7524e100-c0ef-11eb-8f6f-537c1982a7df.gif)

- Purple circle represents the possession crown
- Green line means the crown is being gravitated towards that character
- Red line means the crown is not being gravitated towards that character
- Cyan circle represents the minimum distance for the crown to start gravitating towards a character
- White circle represents the furthest distance a crown can be before it stops gravitating towards a character it is currently attracted too.

![wVsNWH06Gp](https://user-images.githubusercontent.com/60585677/120074261-2297f480-c0f0-11eb-8a83-3afd8128ed94.gif)

This one is frame by frame analysis. Anyways, the solution to this is to use proportional navigation. Its basically how missiles move towards a target - instead of chasing the target, or gravitating towards it, we instead try to intercept a target along the target's path and this results in our 'missile' being able to lock on to a character and chase him down without needing to be at absurd speeds that would inevitably bring up some inconsistent collisions when handling collision boxes @ high speeds. 

Proportional navigation article: https://www.moddb.com/members/blahdy/blogs/gamedev-introduction-to-proportional-navigation-part-i

However, the maths is sorta complicated for me. Luckily, someone posted an example of how to use proportional navigation in Unity in a 3D system (which would be easy to convert into 2D for my needs). 

Btw, here is my game design document (I will post it in my readme later & my game design document gets updated overtime): 
[Game Design Document.docx](https://github.com/NfagieYansaneh/Possession/files/6564840/Game.Design.Document.docx)

Here are the controls for the game. Note that these are the controls for the latest develop build so some controls may not work on your release build.

WASD / D-pad / Joystick - move
H / West button (Controller) - Light attack (No visual feedback yet)
J / North button (Controller) - Heavy attack (No visual feedback yet)
U / East button (Controller) - Throw possession crown (Uses ur movement keys to know where you are throwing)
K / Right trigger (Controller) - Basic ability (No visual feedback yet)
L / Left trigger (Controller) - Ultimate ability (No visual feedback yet)

Shift / Left or Right bumpers (Controller) - Dodge (Uses ur movement keys to know where you are dodging. Furthermore, stand still while dodging to do a neutral dodge)

Space - Jump (You can double jump)

i'll update the readme later but do note that I will be changing the keyboard & controller layout in the future.
