### ISSUE TITLE
I think I broke something

### ISSUE THREAD

**Issue by Estebene** [NfagieYansaneh/Possession#3]
![image](https://user-images.githubusercontent.com/49330942/120618185-f0e7aa80-c4ae-11eb-9334-a99d3adb4595.png)

**Comment by NfagieYansaneh** [comment]
Lol, I have never had that happened to me before. Anyways, this bug is problem happening because when you jump onto another player, ground collision is no longer being detected. Thus, the character thinks its still falling, so it continues to accelerate downwards until it breaks like this. This fix is quite easy, I just need to ignore character-to-character collision. So ill fix that in my upcoming patch.
