### ISSUE TITLE
If you jump then hold shift you stop and hover

### ISSUE THREAD

**Issue by Estebene** [NfagieYansaneh/Possession#4]

**Comment by NfagieYansaneh** [comment]
Oh, that is the neutral dodge which involves you dodging and becoming invulnerable for X amount of frames whilst not actually moving. There isn't proper feedback yet when you carry out this action though, so it appears as if it were a bug. I got the idea of neutral dodging from brawlhalla. However, I may turn neutral dodge into a parry. Therefore, if you were to be attacked while parrying, you stun that enemy for a bit and thus allow you to do a free hit. I got that parry idea from rivals of aether.

Although, there is nothing to dodge right now in my game since there are no attack animations.
